export const loadingTips = [
  // Original tips (1–20)
  "Protein helps preserve muscle while losing fat",
  "Drink water before meals to feel fuller",
  "Sleep 7-9 hours for optimal metabolism",
  "Meal prep saves time and keeps you on track",
  "Fiber-rich foods keep you satisfied longer",
  "Don't skip breakfast - it fuels your day",
  "Consistency beats perfection every time",
  "Small changes lead to big results",
  "Vegetables should fill half your plate",
  "Healthy fats support hormone balance",
  "Plan your meals to avoid impulse eating",
  "Progress, not perfection, is the goal",
  "Your body is unique - listen to it",
  "Chewing slowly aids digestion",
  "Colorful plates mean diverse nutrients",
  "Rest days are part of the process",
  "Stress can sabotage weight loss",
  "Track your progress, not just the scale",
  "Protein at every meal supports muscle",
  "Hydration improves energy and focus",

  // New tips (21–500)
  "Aim for 1.6–2.2g protein per kg bodyweight for muscle gains",
  "Eat protein first in meals to spike satiety",
  "Whey protein post-workout speeds recovery",
  "Cottage cheese before bed fuels overnight muscle repair",
  "Leucine-rich foods trigger muscle protein synthesis",
  "Spread protein across 4–5 meals for best results",
  "Greek yogurt packs more protein than regular",
  "Eggs are nature's perfect protein source",
  "Combine plant proteins for complete amino profile",
  "Protein shakes beat hunger between meals",
  "Prioritize lean meats for high protein low calories",
  "Casein digests slowly – ideal for bedtime",
  "Tofu absorbs flavors and delivers plant protein",
  "Lentils + rice = complete vegan protein",
  "Salmon provides protein + omega-3s for joints",
  "Chicken breast is low-fat muscle fuel",
  "Quark cheese is protein-dense and versatile",
  "Add collagen to coffee for joint & skin support",
  "Protein timing around workouts maximizes gains",
  "Don't fear red meat – choose lean cuts",
  "Tempeh offers fermented protein benefits",
  "Edamame is a complete plant protein snack",
  "Turkey is leaner than most beef",
  "Protein helps preserve muscle in a deficit",
  "Aim for 20–40g protein per meal",
  "Nuts add protein + healthy fats",
  "Seitan is wheat-based protein powerhouse",
  "Bone broth provides collagen protein",
  "Protein curbs late-night cravings",
  "High-protein breakfast stabilizes blood sugar",
  "Muscle needs protein even on rest days",
  "Pea protein is hypoallergenic and effective",
  "Hemp seeds deliver complete plant protein",
  "Chia seeds boost protein in smoothies",
  "Protein powder in oats upgrades breakfast",
  "Tuna cans are portable protein bombs",
  "Sardines offer protein + calcium",
  "Cod is lean white fish protein",
  "Shrimp is low-cal high-protein",
  "Bison is leaner red meat alternative",
  "Venison packs protein with low fat",
  "Lamb provides zinc for testosterone",
  "Duck breast is flavorful protein",
  "Protein supports immune function",
  "Add protein to salads for fullness",
  "Protein helps thermic effect of food",
  "Casein + whey blend for sustained release",
  "Protein prevents muscle catabolism",
  "Egg whites for pure low-fat protein",
  "Protein intake preserves metabolism",
  "Fermented dairy protein aids gut health",
  "Protein + fiber combo kills hunger",
  "High protein diets boost dopamine",
  "Protein supports thyroid function",
  "Add protein to veggie soups",
  "Protein helps regulate appetite hormones",
  "Leucine threshold ~2.5–3g per meal",
  "Protein timing matters less than total",
  "Over 40? Prioritize protein more",
  "Women need protein for muscle too",
  "Protein aids fat oxidation",
  "High protein = better body comp",
  "Protein reduces ghrelin (hunger hormone)",
  "Protein increases GLP-1 (satiety)",
  "Add eggs to stir-fries for protein",
  "Protein supports bone density",
  "High protein helps sleep quality",
  "Protein curbs emotional eating",
  "Protein + resistance training = gains",
  "Don't skip protein on cut days",
  "Protein powder in yogurt boosts macros",
  "Protein helps maintain strength",
  "High protein diets improve mood",
  "Protein supports liver detox",
  "Add protein to popcorn for snack upgrade",
  "Protein prevents rebound weight gain",
  "Protein + veggies = nutrient density",
  "High protein lowers blood pressure",
  "Protein aids wound healing",
  "Protein is thermogenic – burns calories",
  "Start day with 500ml water",
  "Dehydration mimics hunger",
  "Green tea boosts metabolism slightly",
  "Black coffee enhances fat burning",
  "Herbal teas count toward hydration",
  "Add lemon to water for flavor + vitamin C",
  "Drink water with electrolytes post-sweat",
  "Cold water burns extra calories",
  "Hydrate before coffee/tea",
  "Sparkling water curbs soda cravings",
  "Track water intake daily",
  "Water improves skin elasticity",
  "Hydration supports kidney function",
  "Drink during meals for fullness",
  "Infuse water with cucumber/mint",
  "Avoid sugary drinks entirely",
  "Bone broth hydrates + adds collagen",
  "Water first thing boosts alertness",
  "Hydrate consistently, not all at once",
  "Water aids nutrient transport",
  "Proper hydration prevents headaches",
  "Drink more in heat or workouts",
  "Coconut water for natural electrolytes",
  "Water supports joint lubrication",
  "Hydration improves workout performance",
  "Avoid alcohol dehydration",
  "Water flushes toxins",
  "Hydrate to optimize hormones",
  "Water + fiber prevents constipation",
  "Drink before snacking",
  "Hydration boosts cognitive function",
  "Water supports thermoregulation",
  "Add berries to water for antioxidants",
  "Hydration aids weight management",
  "Water improves mood stability",
  "Stay ahead of thirst signal",
  "Hydration enhances recovery",
  "Water supports gut motility",
  "Drink with every meal/snack",
  "Hydration = better sleep",
  "Track habits, not just calories",
  "One small change per week",
  "Mindful eating prevents overeating",
  "Eat without screens for awareness",
  "Plate method: half veggies",
  "Batch cook on Sundays",
  "Eat slowly – 20 min minimum",
  "Hunger scale 1–10 guide",
  "Celebrate non-scale victories",
  "Journal food feelings",
  "Build routines, not restrictions",
  "Forgive slip-ups quickly",
  "Focus on addition, not subtraction",
  "Environment shapes choices",
  "Prep snacks in advance",
  "Use smaller plates",
  "Eat at table, not couch",
  "Batch chop veggies weekly",
  "Set phone reminders to eat",
  "Review week every Sunday",
  "Pair new habit with old one",
  "Visualize goals daily",
  "Gratitude for body progress",
  "Avoid all-or-nothing thinking",
  "Reward consistency, not perfection",
  "Listen to hunger cues",
  "Meal time ritual boosts adherence",
  "Declutter kitchen junk",
  "Shop perimeter of store",
  "Read labels for hidden sugar",
  "Cook at home 80% time",
  "Eat protein + fat first",
  "Walk after meals for digestion",
  "Morning sunlight sets rhythm",
  "Cold shower boosts dopamine",
  "Breathwork reduces stress eating",
  "Stand more, sit less",
  "NEAT adds up daily",
  "Sun exposure for vitamin D",
  "Nature walks lower cortisol",
  "Journal wins weekly",
  "Accountability partner helps",
  "Progress photos motivate",
  "Body measurements > scale",
  "Focus on strength gains",
  "Rest when needed",
  "Sleep hygiene is key",
  "Limit blue light evening",
  "Magnesium before bed",
  "Consistent wake time",
  "No phone 1h before sleep",
  "Dark cool bedroom",
  "Wind-down routine",
  "Track sleep quality",
  "Nap strategically",
  "Stress management = better choices",
  "Meditation 5 min daily",
  "Gratitude practice",
  "Hobbies reduce boredom eating",
  "Social support matters",
  "Community boosts adherence",
  "Learn from setbacks",
  "Curiosity over judgment",
  "Experiment with foods",
  "Seasonal eating fresh",
  "Variety prevents boredom",
  "Season meals creatively",
  "Spices add flavor zero cal",
  "Herbs elevate simple meals",
  "Batch sauces weekly",
  "Freeze portions",
  "Label meal preps",
  "Rotate proteins weekly",
  "Try new veggie each week",
  "Shop with list",
  "Avoid shopping hungry",
  "Budget for quality food",
  "Invest in good containers",
  "Clean as you cook",
  "Enjoy process, not just results",
  "Whole foods over processed",
  "Rainbow veggies for micros",
  "Berries lowest sugar fruit",
  "Avocado healthy fat source",
  "Olive oil for cooking/dressing",
  "Nuts in moderation",
  "Seeds for omega-3 boost",
  "Sweet potato complex carb",
  "Oats sustained energy",
  "Quinoa complete carb + protein",
  "Brown rice better than white",
  "Legumes fiber + protein",
  "Fermented foods gut health",
  "Kimchi sauerkraut yogurt",
  "Dark chocolate 70%+ cocoa",
  "Green tea antioxidants",
  "Turmeric + black pepper",
  "Ginger aids digestion",
  "Garlic immune support",
  "Onions prebiotic",
  "Cruciferous veggies detox",
  "Broccoli powerhouse",
  "Spinach iron + folate",
  "Kale nutrient dense",
  "Carrots beta-carotene",
  "Beets nitric oxide",
  "Mushrooms vitamin D",
  "Tomatoes lycopene",
  "Bell peppers vitamin C",
  "Apples fiber pectin",
  "Bananas potassium",
  "Citrus vitamin C boost",
  "Kiwi more C than orange",
  "Pineapple bromelain",
  "Watermelon hydration",
  "Avocado toast upgrade",
  "Eggs versatile superfood",
  "Fatty fish omega-3",
  "Walnuts brain food",
  "Almonds vitamin E",
  "Chia pudding overnight",
  "Flaxseeds ground fresh",
  "Pumpkin seeds zinc",
  "Sunflower seeds vitamin E",
  "Coconut oil MCTs",
  "Ghee high smoke point",
  "Butter in moderation",
  "Limit seed oils",
  "Choose extra virgin olive",
  "Avoid trans fats",
  "Read ingredient lists",
  "Low sugar yogurt plain",
  "Kefir probiotic rich",
  "Cheese fermented dairy",
  "Limit processed meats",
  "Choose grass-fed when possible",
  "Organic produce reduces pesticides",
  "Frozen veggies retain nutrients",
  "Canned fish convenient",
  "Beans cheap protein",
  "Lentil soup hearty",
  "Chickpeas versatile",
  "Black beans fiber king",
  "Edamame snack pods",
  "Tofu scramble breakfast",
  "Tempeh stir-fry",
  "Seitan meat substitute",
  "Nut butters natural",
  "Hummus dip veggies",
  "Guacamole healthy fat",
  "Salsa low-cal flavor",
  "Mustard zero cal",
  "Vinegar appetite control",
  "Hot sauce metabolism",
  "Herbs fresh flavor",
  "Spices variety",
  "Cinnamon blood sugar",
  "Cayenne thermogenic",
  "Ginger tea digestion",
  "Peppermint soothes gut",
  "Chamomile relaxes",
  "Rooibos caffeine free",
  "Matcha antioxidants",
  "Kombucha probiotics",
  "Limit fruit juice",
  "Whole fruit better",
  "Dried fruit portion control",
  "Popcorn air-popped",
  "Rice cakes low cal base",
  "Veggie sticks crunch",
  "Hard boiled eggs snack",
  "Jerky lean protein",
  "Cheese sticks portable",
  "Dark chocolate square treat",
  "Frozen berries smoothies",
  "Protein ice cream hack",
  "Greek yogurt parfait",
  "Overnight oats easy",
  "Chia jam low sugar",
  "Smoothie greens hidden",
  "Post-workout window protein + carbs",
  "Carbs after training replenish glycogen",
  "Peri-workout nutrition matters",
  "Pre-workout caffeine boost",
  "Beta-alanine tingles endurance",
  "Creatine daily for strength",
  "Vitamin D sunlight or supp",
  "Magnesium muscle relaxation",
  "Zinc testosterone support",
  "Omega-3 anti-inflammatory",
  "Electrolytes during sweat",
  "Foam roll recovery",
  "Stretch daily mobility",
  "Active recovery walks",
  "Sleep repairs muscle",
  "Cold exposure resilience",
  "Sauna recovery benefits",
  "Breathing exercises calm",
  "Sunrise light circadian",
  "No food 3h before bed",
  "Fasting windows optional",
  "Intermittent fasting fat loss",
  "Time-restricted eating",
  "Eat last meal early",
  "Breakfast skippers vary",
  "Carb cycle training days",
  "Refeed days metabolism",
  "Reverse diet post-cut",
  "Maintenance phase learn",
  "Track macros consistency",
  "Weigh food accuracy",
  "App logging builds awareness",
  "Weekly average matters",
  "80/20 rule sustainable",
  "Treats in moderation",
  "Flexible dieting works",
  "Intuitive eating advanced",
  "Hunger full cues",
  "Mindful portions",
  "Plate balance visually",
  "Chew 30 times",
  "Distraction-free meals",
  "Family meals connection",
  "Cook together fun",
  "Teach kids healthy",
  "Grocery shop prepared",
  "List + app sync",
  "Seasonal produce fresh",
  "Farmers market variety",
  "Grow herbs windowsill",
  "Compost scraps",
  "Reduce food waste",
  "Batch freeze soups",
  "Portion freezer bags",
  "Thaw overnight",
  "Reheat gently nutrients",
  "Spice rubs flavor",
  "Marinate protein",
  "Air fry low oil",
  "Steam veggies retain",
  "Roast for caramelization",
  "Grill lean meats",
  "Stir-fry quick",
  "Slow cooker easy",
  "Instant pot fast",
  "Sheet pan dinners",
  "One-pot meals",
  "Mason jar salads",
  "Bento box prep",
  "Snack packs portable",
  "Travel healthy hacks",
  "Airport choices wisely",
  "Hotel room eats",
  "Restaurant swaps smart",
  "Share dessert",
  "Appetizer as meal",
  "Veggie sides first",
  "Sauce on side",
  "Half portion option",
  "Walk after dinner",
  "Social eating balance",
  "Alcohol moderation",
  "Mixers water/soda",
  "Hangover prevention hydrate",
  "Morning recovery smoothie",
  "Weekend reset meal",
  "Sunday prep ritual",
  "Friday treat planned",
  "Holiday strategy",
  "Vacation mindset flexible",
  "Back on track fast",
  "No guilt cycle",
  "Compassion self-talk",
  "Body positive journey",
  "Strength over scale",
  "Health span focus",
  "Longevity habits",
  "Aging gracefully nutrition",
  "Bone health calcium D",
  "Heart health omega-3",
  "Add cinnamon to coffee",
  "Vinegar before carb meal",
  "Apple cider vinegar shot",
  "Psyllium husk fiber",
  "Glucomannan satiety",
  "Cayenne in water",
  "Ginger lemon tea",
  "Turmeric golden milk",
  "Matcha latte energy",
  "Bone broth sip",
  "Kombucha gut",
  "Sauerkraut side",
  "Kimchi spicy kick",
  "Miso soup umami",
  "Natto fermented soy",
  "Kefir morning ritual",
  "Yogurt bowl base",
  "Smoothie greens powder",
  "Collagen in drinks",
  "Electrolyte packets",
  "LMNT salty hydration",
  "Pickle juice cramps",
  "Taurine energy",
  "L-theanine calm focus",
  "Ashwagandha stress",
  "Rhodiola adaptogen",
  "Mushroom coffee",
  "Cacao raw energy",
  "Beetroot nitrate",
  "Pomegranate antioxidants",
  "Blueberries brain",
  "Acai bowl treat",
  "Dragon fruit exotic",
  "Passion fruit vitamin C",
  "Papaya digestion",
  "Mango vitamin A",
  "Peach summer fiber",
  "Pear juicy fiber",
  "Plum low cal",
  "Cherries melatonin",
  "Grapes resveratrol",
  "Strawberries low sugar",
  "Raspberries fiber king",
  "Blackberries antioxidants",
  "Cranberries urinary",
  "Goji berries super",
  "Mulberries iron",
  "Elderberry immune",
  "Seaweed iodine",
  "Spirulina protein",
  "Chlorella detox",
  "Wheatgrass shot",
  "Barley grass green",
  "Algae omega-3",
  "Nutritional yeast B12",
  "Hemp hearts omega",
  "Pumpkin seed butter",
  "Tahini calcium",
  "Sunbutter allergy free",
  "Almond butter toast",
  "Peanut butter natural",
  "Cashew cream dairy free",
  "Coconut yogurt alternative",
  "Oat milk neutral",
  "Almond milk low cal",
  "Soy milk protein",
  "Pea milk high protein",
  "Macadamia milk creamy",
  "Walnut milk omega",
  "Flax milk ALA",
  "Rice milk light",
  "Horchata homemade",
  "Chai spice warm",
  "Turmeric latte golden",
  "Cacao hot chocolate",
  "Peppermint tea calm",
  "Rooibos red tea",
  "Hibiscus tart",
  "Yerba mate energy",
  "Enjoy food journey"
];

export function getRandomTip(): string {
  return loadingTips[Math.floor(Math.random() * loadingTips.length)];
}