export const loadingTips = [
  // Original tips (1–20)
  "Adequate protein preserves muscle mass during fat loss periods",
  "Drink water before meals to increase feelings of fullness",
  "Aim for 7-9 hours sleep nightly for better metabolism",
  "Meal prep weekly to save time and stay consistent",
  "Fiber-rich foods keep you feeling satisfied much longer",
  "Never skip breakfast since it fuels your whole day",
  "Consistency always beats chasing unrealistic perfection",
  "Small sustainable changes create big long-term results",
  "Fill half your plate with vegetables every meal",
  "Healthy fats are essential for balanced hormone levels",
  "Plan meals ahead to avoid impulsive food choices",
  "Focus on steady progress instead of perfect results",
  "Your body is unique so listen to its signals",
  "Chew food slowly to improve digestion and absorption",
  "Colorful plates deliver a wide variety of nutrients",
  "Rest days are essential for recovery and gains",
  "Chronic stress can seriously hinder weight loss progress",
  "Track multiple progress markers beyond just scale weight",
  "Include protein at every meal for muscle support",
  "Proper hydration boosts daily energy and mental focus",

  // New tips (21–500)
  "Target 1.6-2.2g protein per kg bodyweight for gains",
  "Eat protein first in meals to boost satiety faster",
  "Whey protein post-workout accelerates muscle recovery significantly",
  "Cottage cheese before bed supports overnight muscle repair",
  "Leucine-rich foods effectively trigger muscle protein synthesis",
  "Spread protein over 4-5 meals for optimal utilization",
  "Greek yogurt delivers significantly more protein than regular",
  "Eggs provide nature's most complete protein profile",
  "Combine plant proteins to achieve complete amino acids",
  "Protein shakes effectively control hunger between meals",
  "Choose lean meats for maximum protein minimal calories",
  "Casein digests slowly making it perfect for bedtime",
  "Tofu absorbs flavors while providing quality plant protein",
  "Lentils and rice together create complete vegan protein",
  "Salmon delivers protein plus joint-supporting omega-3 fatty acids",
  "Chicken breast offers low-fat high-quality muscle fuel",
  "Quark cheese is extremely protein-dense and highly versatile",
  "Add collagen to coffee for better joints and skin",
  "Time protein around workouts to maximize muscle gains",
  "Choose lean red meat cuts without unnecessary fear",
  "Tempeh provides fermented protein with extra gut benefits",
  "Edamame serves as complete plant protein snack",
  "Turkey is typically leaner than most beef cuts",
  "Protein prevents muscle loss during calorie deficits",
  "Aim for 20-40g protein at each meal",
  "Nuts combine protein with beneficial healthy fats",
  "Seitan is powerful wheat-based high-protein meat alternative",
  "Bone broth supplies easily absorbed collagen protein",
  "Higher protein intake reduces late-night food cravings",
  "High-protein breakfast stabilizes blood sugar all morning",
  "Muscles need protein daily even on rest days",
  "Pea protein is hypoallergenic and highly effective",
  "Hemp seeds provide complete plant-based protein source",
  "Chia seeds easily boost protein in smoothies",
  "Protein powder in oats transforms breakfast nutrition",
  "Canned tuna offers convenient portable protein option",
  "Sardines provide protein plus bone-building calcium",
  "Cod delivers lean high-quality white fish protein",
  "Shrimp is extremely high protein very low calorie",
  "Bison offers leaner alternative to regular red meat",
  "Venison provides high protein with minimal fat",
  "Lamb supplies zinc crucial for testosterone production",
  "Duck breast delivers flavorful premium protein source",
  "Protein plays vital role in immune system function",
  "Add protein to salads for greater meal satisfaction",
  "Protein has highest thermic effect burning more calories",
  "Casein-whey blend provides sustained protein release",
  "Adequate protein prevents unwanted muscle breakdown",
  "Egg whites offer pure protein without fat",
  "High protein intake helps preserve metabolic rate",
  "Fermented dairy proteins promote healthier gut microbiome",
  "Protein plus fiber combination controls hunger best",
  "High-protein diets naturally increase dopamine levels",
  "Protein supports optimal thyroid hormone function",
  "Add protein to soups for complete nutrition",
  "Protein regulates key appetite controlling hormones",
  "Hit leucine threshold of 2.5-3g per meal",
  "Total daily protein matters more than timing",
  "After age 40 increase protein intake priority",
  "Women benefit greatly from higher protein too",
  "Protein enhances fat oxidation during energy use",
  "Higher protein improves overall body composition",
  "Protein lowers ghrelin the main hunger hormone",
  "Protein boosts GLP-1 for stronger satiety signals",
  "Add eggs to stir-fries for easy protein boost",
  "Protein contributes to maintaining bone density",
  "Higher protein intake improves sleep quality",
  "Protein reduces emotional and stress-driven eating",
  "Protein plus resistance training maximizes muscle gains",
  "Never skip protein even during cutting phases",
  "Protein powder in yogurt boosts macros significantly",
  "Protein helps maintain strength while losing fat",
  "High-protein diets frequently improve mood stability",
  "Protein supports natural liver detoxification processes",
  "Add protein to popcorn for healthier snack",
  "Protein prevents rebound weight gain after diets",
  "Protein with vegetables maximizes nutrient density",
  "High-protein diets can lower blood pressure",
  "Protein accelerates recovery and wound healing",
  "Protein is highly thermogenic burning extra calories",
  "Start every day with 500ml water minimum",
  "Dehydration often feels exactly like hunger",
  "Green tea provides small natural metabolism boost",
  "Black coffee can enhance fat burning effects",
  "Herbal teas count fully toward hydration goals",
  "Add lemon to water for flavor and vitamin C",
  "Post-workout water with electrolytes aids recovery",
  "Cold water slightly increases calorie burn",
  "Hydrate well before coffee or tea consumption",
  "Sparkling water helps replace sugary soda cravings",
  "Track daily water intake for consistent hydration",
  "Hydration significantly improves skin elasticity",
  "Proper hydration supports healthy kidney function",
  "Drink during meals to enhance satiety signals",
  "Infuse water with cucumber mint for taste",
  "Eliminate all sugary drinks for better results",
  "Bone broth hydrates while adding collagen protein",
  "Morning water boosts alertness and metabolism",
  "Hydrate steadily instead of large amounts occasionally",
  "Water transports essential nutrients throughout body",
  "Adequate hydration prevents frequent headaches",
  "Drink more water during heat or exercise",
  "Coconut water naturally replenishes lost electrolytes",
  "Hydration maintains proper joint lubrication",
  "Good hydration improves workout performance noticeably",
  "Avoid alcohol to prevent dehydration effects",
  "Water helps flush toxins from body",
  "Hydration optimizes hormone balance and function",
  "Water plus fiber prevents digestive constipation",
  "Drink before snacking to confirm true hunger",
  "Hydration enhances cognitive function and focus",
  "Water regulates body temperature effectively",
  "Add berries to water for antioxidant boost",
  "Hydration plays major role in weight control",
  "Proper hydration stabilizes mood and energy",
  "Stay ahead of thirst for optimal hydration",
  "Hydration speeds workout recovery significantly",
  "Water supports healthy gut movement",
  "Drink water with every meal and snack",
  "Hydration contributes to better sleep quality",
  "Track habits alongside calorie intake",
  "Add one small positive change weekly",
  "Mindful eating reduces unconscious overeating significantly",
  "Eat without screens for greater food awareness",
  "Half plate vegetables using simple plate method",
  "Batch cook healthy meals every Sunday",
  "Eat slowly taking at least 20 minutes",
  "Use 1-10 hunger scale as guide",
  "Celebrate all non-scale victories regularly",
  "Journal food choices and emotional connections",
  "Build sustainable routines over strict restrictions",
  "Forgive mistakes quickly and continue forward",
  "Focus on adding healthy foods primarily",
  "Your environment strongly influences daily choices",
  "Prepare healthy snacks ahead of time",
  "Use smaller plates for natural portion control",
  "Eat at table instead of couch",
  "Batch chop vegetables once per week",
  "Set reminders for regular balanced meals",
  "Review progress every Sunday evening",
  "Pair new habits with existing ones",
  "Visualize fitness goals every single day",
  "Practice gratitude for body and progress",
  "Avoid extreme all-or-nothing mindset",
  "Reward consistency over occasional perfection",
  "Listen carefully to true hunger cues",
  "Create pleasant meal rituals for adherence",
  "Remove junk food from kitchen environment",
  "Shop grocery store perimeter for whole foods",
  "Read labels to identify hidden sugars",
  "Cook at home 80% of time",
  "Eat protein and fat first each meal",
  "Walk after meals to improve digestion",
  "Morning sunlight regulates circadian rhythm naturally",
  "Cold showers increase dopamine and alertness",
  "Breathwork reduces stress and emotional eating",
  "Stand more and reduce sitting time",
  "Daily NEAT activities burn extra calories",
  "Sun exposure provides natural vitamin D",
  "Nature walks effectively lower cortisol levels",
  "Journal weekly wins for ongoing motivation",
  "Accountability partner increases success significantly",
  "Progress photos show changes scale misses",
  "Measurements often better than scale weight",
  "Focus on increasing strength over time",
  "Rest properly when body signals need",
  "Sleep hygiene is absolutely crucial",
  "Limit evening blue light exposure",
  "Magnesium supplement aids relaxation and sleep",
  "Maintain consistent daily wake time",
  "No screens one hour before bed",
  "Keep bedroom dark cool and quiet",
  "Establish relaxing pre-bed wind-down routine",
  "Track sleep quality for improvements",
  "Use strategic short naps when needed",
  "Stress management improves food choice quality",
  "Meditate five minutes every day",
  "Daily gratitude practice improves mindset",
  "Hobbies prevent boredom-triggered eating",
  "Social support boosts long-term adherence",
  "Community involvement increases motivation greatly",
  "Learn from setbacks instead of quitting",
  "Approach challenges with curiosity not judgment",
  "Experiment regularly with new healthy foods",
  "Seasonal eating ensures freshest produce",
  "Variety prevents diet fatigue and boredom",
  "Creative seasoning enhances flavor naturally",
  "Spices add taste without extra calories",
  "Fresh herbs elevate simple healthy dishes",
  "Batch prepare sauces for quick use",
  "Freeze portions for future convenience",
  "Label all meal preps clearly",
  "Rotate proteins weekly for variety",
  "Try one new vegetable every week",
  "Always grocery shop with list",
  "Never shop while hungry",
  "Budget for higher quality foods",
  "Invest in quality storage containers",
  "Clean kitchen while cooking meals",
  "Enjoy cooking process beyond just results",
  "Prioritize whole foods over processed",
  "Rainbow vegetables provide diverse micronutrients",
  "Berries are lowest-sugar fruit options",
  "Avocado supplies healthy monounsaturated fats",
  "Extra virgin olive oil for cooking",
  "Nuts in moderation for healthy fats",
  "Seeds boost omega-3 intake naturally",
  "Sweet potatoes offer complex carbohydrates",
  "Oats deliver sustained daily energy",
  "Quinoa combines carbs and complete protein",
  "Brown rice superior to white rice",
  "Legumes provide fiber and plant protein",
  "Fermented foods improve gut microbiome",
  "Include kimchi sauerkraut and yogurt",
  "Dark chocolate 70%+ as occasional treat",
  "Green tea rich in powerful antioxidants",
  "Turmeric plus pepper for better absorption",
  "Ginger reduces nausea and aids digestion",
  "Garlic boosts natural immune defense",
  "Onions feed beneficial gut bacteria",
  "Cruciferous vegetables support natural detoxification",
  "Broccoli packs exceptional nutrient density",
  "Spinach supplies iron and folate",
  "Kale is extremely nutrient dense",
  "Carrots provide vision-supporting beta-carotene",
  "Beets increase nitric oxide production",
  "Mushrooms offer natural vitamin D",
  "Tomatoes contain protective lycopene",
  "Bell peppers loaded with vitamin C",
  "Apples deliver fiber and pectin",
  "Bananas supply quick potassium boost",
  "Citrus fruits increase vitamin C intake",
  "Kiwi contains more C than oranges",
  "Pineapple supplies digestive enzyme bromelain",
  "Watermelon excellent for summer hydration",
  "Upgrade avocado toast with healthy toppings",
  "Eggs are ultimate versatile superfood",
  "Fatty fish richest omega-3 source",
  "Walnuts support brain health significantly",
  "Almonds provide skin-protecting vitamin E",
  "Overnight chia pudding easy breakfast",
  "Grind flaxseeds fresh for benefits",
  "Pumpkin seeds rich in zinc",
  "Sunflower seeds good vitamin E source",
  "Coconut oil contains energy MCTs",
  "Ghee perfect high smoke point fat",
  "Butter acceptable in small moderation",
  "Limit inflammatory industrial seed oils",
  "Always choose extra virgin olive",
  "Avoid trans fats at all costs",
  "Read full ingredient lists carefully",
  "Plain yogurt without added sugar",
  "Kefir packed with diverse probiotics",
  "Cheese as quality fermented dairy",
  "Limit highly processed meat products",
  "Grass-fed meat when budget allows",
  "Organic produce minimizes pesticide exposure",
  "Frozen vegetables retain excellent nutrients",
  "Canned fish convenient protein source",
  "Beans inexpensive high-quality protein",
  "Lentil soup hearty satisfying meal",
  "Chickpeas incredibly versatile legume",
  "Black beans fiber powerhouse",
  "Edamame pods healthy snack",
  "Tofu scramble tasty breakfast alternative",
  "Tempeh excellent in stir-fries",
  "Seitan high-protein meat substitute",
  "Natural nut butters no additives",
  "Hummus perfect vegetable dip",
  "Guacamole healthy fat source",
  "Salsa adds flavor zero calories",
  "Mustard zero-calorie flavor enhancer",
  "Vinegar helps control blood sugar",
  "Hot sauce potential metabolism boost",
  "Fresh herbs maximum natural flavor",
  "Variety spices keep meals exciting",
  "Cinnamon stabilizes blood sugar levels",
  "Cayenne pepper mild thermogenic effect",
  "Ginger tea soothes digestion",
  "Peppermint tea calms stomach",
  "Chamomile tea promotes relaxation",
  "Rooibos naturally caffeine-free tea",
  "Matcha loaded with antioxidants",
  "Kombucha supplies gut probiotics",
  "Limit fruit juice high sugar",
  "Whole fruit always superior choice",
  "Portion control with dried fruit",
  "Air-popped popcorn healthy snack base",
  "Rice cakes low-calorie foundation",
  "Veggie sticks satisfying crunchy snack",
  "Hard-boiled eggs portable protein",
  "Lean jerky convenient protein",
  "Cheese sticks easy portable snack",
  "Dark chocolate square mindful treat",
  "Frozen berries perfect smoothie addition",
  "Homemade protein ice cream hack",
  "Greek yogurt parfait layered treat",
  "Overnight oats simple meal prep",
  "Low-sugar homemade chia jam",
  "Hide greens in tasty smoothies",
  "Post-workout protein plus carbs optimal",
  "Carbs after training restore glycogen",
  "Peri-workout nutrition enhances performance",
  "Pre-workout caffeine improves energy",
  "Beta-alanine increases muscular endurance",
  "Daily creatine builds strength",
  "Vitamin D from sun or supplement",
  "Magnesium relaxes muscles and nerves",
  "Zinc supports testosterone production",
  "Omega-3 reduces systemic inflammation",
  "Electrolytes essential during heavy sweating",
  "Foam rolling speeds muscle recovery",
  "Daily stretching improves mobility",
  "Light walks excellent active recovery",
  "Sleep primary muscle repair time",
  "Cold exposure builds mental resilience",
  "Sauna sessions aid recovery",
  "Breathing exercises reduce stress",
  "Morning sunlight sets circadian rhythm",
  "No food three hours before bed",
  "Intermittent fasting optional fat loss tool",
  "Time-restricted eating simple effective strategy",
  "Finish eating earlier in evening",
  "Some thrive skipping breakfast",
  "Carb cycling around training days",
  "Periodic refeeds boost metabolism",
  "Reverse diet after cutting phase",
  "Maintenance teaches long-term balance",
  "Track macros for consistent results",
  "Weigh food for accurate tracking",
  "App logging increases food awareness",
  "Weekly averages matter most",
  "80/20 approach ensures sustainability",
  "Planned treats maintain sanity",
  "Flexible dieting proven effective",
  "Intuitive eating for advanced stage",
  "Honor true hunger and fullness",
  "Mindful portions prevent overeating",
  "Visual plate balance simple guide",
  "Chew thoroughly thirty times",
  "Distraction-free meals improve satisfaction",
  "Family meals strengthen healthy habits",
  "Cook together for enjoyment",
  "Teach children balanced nutrition early",
  "Prepared grocery shopping prevents impulses",
  "Sync shopping list with app",
  "Seasonal produce freshest and cheapest",
  "Farmers markets offer great variety",
  "Grow herbs on kitchen windowsill",
  "Compost scraps reduce waste",
  "Reduce overall food waste",
  "Batch freeze soups for later",
  "Portion meals into freezer bags",
  "Thaw overnight in fridge",
  "Gentle reheating preserves nutrients",
  "Spice rubs enhance flavor naturally",
  "Marinate proteins for better taste",
  "Air fryer reduces oil use",
  "Steaming vegetables retains maximum nutrients",
  "Roasting creates delicious caramelization",
  "Grill lean meats healthily",
  "Stir-fry quick nutritious meals",
  "Slow cooker effortless cooking",
  "Instant pot speeds meal prep",
  "Sheet pan dinners minimal cleanup",
  "One-pot meals easy preparation",
  "Mason jar salads stay fresh",
  "Bento boxes perfect portion control",
  "Portable prepped snack packs",
  "Travel with smart healthy options",
  "Choose wisely at airports",
  "Stock hotel room healthy foods",
  "Restaurant smart swaps available",
  "Share desserts control portions",
  "Appetizer can become main meal",
  "Order extra vegetable sides",
  "Sauce always on side",
  "Request half portions when possible",
  "Walk after dinner aids digestion",
  "Balance social eating occasions",
  "Alcohol only strict moderation",
  "Water or soda mixers only",
  "Hydrate heavily prevent hangovers",
  "Recovery smoothie next morning",
  "Weekend reset balanced meal",
  "Sunday evening prep ritual",
  "Plan Friday treat ahead",
  "Holiday eating strategy prepared",
  "Vacation flexible healthy mindset",
  "Return to routine quickly",
  "Avoid guilt after slip-ups",
  "Compassionate positive self-talk",
  "Body positive throughout journey",
  "Strength gains over scale obsession",
  "Focus on long health span",
  "Build sustainable longevity habits",
  "Nutrition key graceful aging",
  "Calcium vitamin D bone health",
  "Omega-3 supports heart health",
  "Cinnamon in coffee blood sugar aid",
  "Vinegar before carbs slows spike",
  "Daily apple cider vinegar shot",
  "Psyllium husk increases fiber intake",
  "Glucomannan expands for satiety",
  "Cayenne pepper water metabolism",
  "Ginger lemon tea digestion aid",
  "Turmeric golden milk anti-inflammatory",
  "Matcha latte sustained energy",
  "Daily bone broth sipping",
  "Kombucha supports gut health",
  "Sauerkraut probiotic side dish",
  "Kimchi adds spicy probiotics",
  "Miso soup umami flavor",
  "Natto fermented soy benefits",
  "Kefir morning probiotic ritual",
  "Yogurt bowl customizable base",
  "Greens powder smoothie boost",
  "Collagen peptides daily drinks",
  "Electrolyte packets convenient hydration",
  "LMNT provides salty electrolyte balance",
  "Pickle juice relieves muscle cramps",
  "Taurine boosts energy levels",
  "L-theanine promotes calm focus",
  "Ashwagandha lowers daily stress",
  "Rhodiola powerful adaptogen herb",
  "Mushroom coffee healthier alternative",
  "Raw cacao natural energy source",
  "Beetroot increases nitric oxide",
  "Pomegranate packed with antioxidants",
  "Blueberries support brain function",
  "Acai bowl nutritious treat",
  "Dragon fruit exotic nutrition",
  "Passion fruit vitamin C rich",
  "Papaya contains digestive enzymes",
  "Mango excellent vitamin A source",
  "Peach provides seasonal fiber",
  "Pear juicy low-calorie fiber",
  "Plum naturally low calorie",
  "Cherries contain natural melatonin",
  "Grapes supply protective resveratrol",
  "Strawberries low sugar fruit",
  "Raspberries extremely fiber rich",
  "Blackberries powerful antioxidant source",
  "Cranberries support urinary tract",
  "Goji berries nutrient-dense superfood",
  "Mulberries high in iron",
  "Elderberry strong immune support",
  "Seaweed natural iodine source",
  "Spirulina complete algae protein",
  "Chlorella powerful detoxification aid",
  "Wheatgrass energizing green shot",
  "Barley grass nutrient powder",
  "Algae plant-based omega-3 source",
  "Nutritional yeast vegan B12",
  "Hemp hearts omega rich",
  "Pumpkin seed butter spread",
  "Tahini excellent calcium source",
  "Sunbutter safe allergy alternative",
  "Almond butter healthy toast",
  "Natural peanut butter choice",
  "Cashew cream dairy-free option",
  "Coconut yogurt plant alternative",
  "Oat milk neutral flavor",
  "Almond milk low-calorie choice",
  "Soy milk decent protein",
  "Pea milk highest protein",
  "Macadamia milk rich creamy",
  "Walnut milk omega source",
  "Flax milk ALA omega",
  "Rice milk lightest option",
  "Homemade horchata refreshing drink",
  "Chai spices warming blend",
  "Golden turmeric latte drink",
  "Hot raw cacao drink",
  "Peppermint tea calming effect",
  "Rooibos antioxidant red tea",
  "Hibiscus tart refreshing tea",
  "Yerba mate natural energy",
  "Enjoy your healthy food journey fully"
];

export function getRandomTip(): string {
  return loadingTips[Math.floor(Math.random() * loadingTips.length)];
}